version: 0.0
os: linux
files:
  - source:  $source_path
    destination:  $destination_path
hooks:
  BeforeInstall:
  - location: Backup_script.sh
    timeout: 300
    runas: root
  AfterInstall:
  - location: Deploy_and_Rollback_script.sh
    timeout: 300
    runas: root
