version: 0.0
os: linux
files:
  - source: 21Sep2020
    destination: /opt/wildfly/standalone/deployments/
hooks:
  BeforeInstall:
  - location: Backup_script.sh
    timeout: 300
    runas: root
  AfterInstall:
  - location: Deploy_and_Rollback_script.sh
    timeout: 300
    runas: root
