version: 0.0
os: linux
files:
  - source: /Deployment_Files_and_Path_ORGINAL_FORMAT.txt
    destination: /opt/wildfly/standalone/deployment/
hooks:
  BeforeInstall:
  - location: Building_Patch_Files.sh
  - location: Post_build.sh
  - location: Backup_script.sh
    timeout: 300
    runas: root
  AfterInstall:
  - location: Deploy_and_Rollback_script.sh
    timeout: 300
    runas: root
